In [1]:
# Zadanie 1

import numpy as np

#Z pythonowym range
table1 = np.array(range(1,101))

#czysty numpy, szybszy
table2 = np.arange(1, 101)
suma = np.sum(table2)
srednia = np.mean(table2)
mediana = np.median(table2)
maksimum = np.max(table2)
minimum = np.min(table2)

print(suma, srednia, mediana, maksimum, minimum)

5050 50.5 50.5 100 1


In [8]:
# Zadanie 2

before = np.array([100, 250, 75, 320, 180, 450, 90])
after = np.array([80, 200, 60, 280, 150, 400, 75])

differences = before - after
print(differences)

discounts = np.round(((differences / before) * 100), 2)
print(discounts)

average_discount = np.round(np.mean(discounts), 2)
print(average_discount)

[20 50 15 40 30 50 15]
[20.   20.   20.   12.5  16.67 11.11 16.67]
16.71


In [19]:
# Zadanie 3

temps = np.array([15, 18, 22, 25, 23, 20, 17, 14, 16, 19, 21, 24])

print(temps[::2])
print(temps[-5:])
print(np.flip(temps, axis=0))
print(temps[temps > 20])

[15 22 23 17 16 21]
[14 16 19 21 24]
[24 21 19 16 14 17 20 23 25 22 18 15]
[22 25 23 21 24]


In [34]:
# Zadanie 5

sales = np.random.randint(10, 100, size=(4, 7))
print(sales)

print(f"Średnie per produkt:", np.mean(sales, axis=1))
print(f"Średnie per dzień: ", np.mean(sales, axis=0))
print(f"Dzień z najwyższą sprzedażą: ", np.argmax(np.sum(sales, axis=0)) + 1)
print(f"Produkt z najniższą średnią sprzedażą: ", np.argmin(np.mean(sales, axis=1)) + 1)

[[73 62 45 92 52 44 86]
 [23 78 43 25 29 97 62]
 [73 50 40 95 86 30 10]
 [21 43 77 73 22 96 52]]
Średnie per produkt: [64.85714286 51.         54.85714286 54.85714286]
Średnie per dzień:  [47.5  58.25 51.25 71.25 47.25 66.75 52.5 ]
Dzień z najwyższą sprzedażą:  4
Produkt z najniższą średnią sprzedażą:  2


In [40]:
# Zadanie 6

grades = np.array([78, 45, 92, 67, 34, 88, 56, 91, 23, 85, 73, 95])

# Znadź wszystkie oceny >= 80
print(grades[grades >= 80])
# Znajdź wszystkie oceny <50 (oceny niedostateczne)
print(grades[grades < 50])
# Ile jest ocen w przedziale [60, 80]
suma = len(grades[(grades > 50) & (grades <= 80)])
print(suma)
# Zmień wszystkie oceny < 50 na 50
grades_modified = grades.copy()
grades_modified[grades < 50] = 50
print(grades_modified)


[92 88 91 85 95]
[45 34 23]
4
[78 50 92 67 50 88 56 91 50 85 73 95]


In [48]:
# Zadanie 7

zera = np.zeros((3, 3))
print(zera)

jedynki = np.ones((4, 4))
print(jedynki)

identycznosci = np.eye(5)
print(identycznosci)

siodemki = np.full((3, 4), 7)
print(siodemki)

linspace = np.linspace(0, 1, 10)
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [53]:
# Zadanie 8

arr = np.arange(1, 13)

change1 = arr.reshape((3, 4))
print(change1)

change2 = arr.reshape((2, 6))
print(change2)

change3 = arr.reshape((4, 3))
print(change3)

flatten = arr.flatten()
print(flatten)

ravel = arr.ravel()
print(ravel)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
