In [1]:
# Zadanie 1

import numpy as np

#Z pythonowym range
table1 = np.array(range(1,101))

#czysty numpy, szybszy
table2 = np.arange(1, 101)
suma = np.sum(table2)
srednia = np.mean(table2)
mediana = np.median(table2)
maksimum = np.max(table2)
minimum = np.min(table2)

print(suma, srednia, mediana, maksimum, minimum)

5050 50.5 50.5 100 1


In [8]:
# Zadanie 2

before = np.array([100, 250, 75, 320, 180, 450, 90])
after = np.array([80, 200, 60, 280, 150, 400, 75])

differences = before - after
print(differences)

discounts = np.round(((differences / before) * 100), 2)
print(discounts)

average_discount = np.round(np.mean(discounts), 2)
print(average_discount)

[20 50 15 40 30 50 15]
[20.   20.   20.   12.5  16.67 11.11 16.67]
16.71


In [19]:
# Zadanie 3

temps = np.array([15, 18, 22, 25, 23, 20, 17, 14, 16, 19, 21, 24])

print(temps[::2])
print(temps[-5:])
print(np.flip(temps, axis=0))
print(temps[temps > 20])

[15 22 23 17 16 21]
[14 16 19 21 24]
[24 21 19 16 14 17 20 23 25 22 18 15]
[22 25 23 21 24]


In [34]:
# Zadanie 5

sales = np.random.randint(10, 100, size=(4, 7))
print(sales)

print(f"Średnie per produkt:", np.mean(sales, axis=1))
print(f"Średnie per dzień: ", np.mean(sales, axis=0))
print(f"Dzień z najwyższą sprzedażą: ", np.argmax(np.sum(sales, axis=0)) + 1)
print(f"Produkt z najniższą średnią sprzedażą: ", np.argmin(np.mean(sales, axis=1)) + 1)

[[73 62 45 92 52 44 86]
 [23 78 43 25 29 97 62]
 [73 50 40 95 86 30 10]
 [21 43 77 73 22 96 52]]
Średnie per produkt: [64.85714286 51.         54.85714286 54.85714286]
Średnie per dzień:  [47.5  58.25 51.25 71.25 47.25 66.75 52.5 ]
Dzień z najwyższą sprzedażą:  4
Produkt z najniższą średnią sprzedażą:  2
